Add MQ filter for BAM files
NBISweden/DNAharvester pull request #64
Opened 2024-12-05 12:30 UTC by verku

MQ >= 25

2024-12-09 14:01 UTC, bilalbioinfo requested changes

2024-12-09 14:01 UTC, bilalbioinfo commented on read-harvester/modules/local/samtools/view_mq/main.nf
> +        ${reference} \\
why do we need reference here?

2024-12-09 14:01 UTC, bilalbioinfo commented on read-harvester/configs/modules.config
> +        ext.args   = { "-q {params.mq} --output-fmt bam" } // mapping quality
missing $
${params.mq}

2024-12-09 14:14 UTC, bilalbioinfo commented on read-harvester/configs/modules.config
> +        ext.args   = { "-q {params.mq} --output-fmt bam" } // mapping quality
we can also remove "--output-fmt" bam to make it simple as by default it is bam!

2024-12-10 10:47 UTC, verku commented
Check that preseq is run after MQ filtering

2024-12-11 06:14 UTC, verku commented on read-harvester/modules/local/samtools/view_mq/main.nf
> +        ${reference} \\
It is most likely not needed, I used the nf-core module as a starting point where it is provided.

2024-12-11 06:15 UTC, verku commented on read-harvester/configs/modules.config
> +        ext.args   = { "-q {params.mq} --output-fmt bam" } // mapping quality
Thanks! The "--output-fmt" flag was provided because the original nf-core module has all sorts of output formats as an option. But with my changes we should remove it!

2024-12-11 06:20 UTC, verku commented on read-harvester/modules/local/samtools/view_mq/main.nf
> +        ${reference} \\
Fixed in commit [c07a28d](https://github.com/NBISweden/LTS-L_Dalen_2302/pull/64/commits/c07a28d97d101cff7764ec792f180ba998611f63)

2024-12-11 06:20 UTC, verku commented on read-harvester/configs/modules.config
> +        ext.args   = { "-q {params.mq} --output-fmt bam" } // mapping quality
Fixed in commit [30cf1f6](https://github.com/NBISweden/LTS-L_Dalen_2302/pull/64/commits/30cf1f6cf07996955713416664bf11d52197c2f3)

2024-12-11 13:50 UTC, merged

2024-12-11 13:50 UTC, bilalbioinfo commented
it works!!

2024-12-11 13:53 UTC, verku commented
Awesome!