Map to a concatenated reference (target + decoy) using the human genome as default decoy
NBISweden/DNAharvester pull request #65
Opened 2024-12-06 10:52 UTC by verku

TO DO:
- The resulting BAM files will be split and analyzed with samtools flagstat
- The pipeline will continue with the BAM file excluding the decoy chromosomes/scaffolds

2024-12-09 16:34 UTC, bilalbioinfo requested changes

2024-12-09 16:34 UTC, bilalbioinfo commented on read-harvester/modules/local/concatenate_target_decoy_refs/main.nf
> +process CONCATENATE_TARGET_DECOY_REFS {
This will create the concat the reference everytime user run the pipeline and index it - will be heavily increase the time to run the pipeline, At cpg, we have a general practice that to create a reference (along with human genomes) and index it in a folder that everyone can access use the same everytime!! 
we should implement it in way that user can provide a link to the target_decoy genome and list of the chr names of decoy genome!
there can be a separate sub-workflow if user want tthe pipeline to create the target+decoy genome and index it!

2024-12-09 16:34 UTC, bilalbioinfo commented on read-harvester/modules/local/concatenate_target_decoy_refs/main.nf
> +process CONCATENATE_TARGET_DECOY_REFS {
we can have a meeting on it!

2024-12-09 16:37 UTC, verku commented
Sounds good, this part didn't work yet anyway!

2024-12-10 10:49 UTC, verku commented
Pipeline implementation

- Concatenated fasta file and BWA index need to be present for the decoy+target genome (same directory)
- The user needs to provide a list of chromosomes from the decoy genome

The pipeline will run

- bwa aln + samse to map reads to the concatenated genome
- samtools faidx
- Split BAM files into decoy and target genome
- Decoy genome BAM: samtools flagstat and multiqc. Is not provided in results folder (i.e. temporary file).
- Target genome BAM → remaining pipeline

2024-12-11 06:41 UTC, closed without merging